import bluetooth

name="server"
target_name="test"
# some random uuid, generated by https://www.famkruithof.net/uuid/uuidgen
uuid="0fee0450-e95f-11e5-a837-0800200c9a66"

def runServer():
    serverSocket=bluetooth.BluetoothSocket(bluetooth.RFCOMM )
    port=bluetooth.PORT_ANY
    serverSocket.bind(("",port))
    serverSocket.listen(1)
    port=serverSocket.getsockname()[1]
    bluetooth.advertise_service( serverSocket, "SampleServer",
                       service_id = uuid,
                       service_classes = [ uuid, bluetooth.SERIAL_PORT_CLASS ],
                       profiles = [ bluetooth.SERIAL_PORT_PROFILE ]
                        )

    inputSocket, address=serverSocket.accept()
    data=inputSocket.recv(1024)
    inputSocket.close()
    serverSocket.close()

runServer()
